0. Cargar las librerias de referencia para el modelo

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt #graficador
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

1. Se procede con la carga de los datos del archivo

In [ ]:
nxl='/content/drive/MyDrive/Analitica de negocios /Base de Datos_Final.xlsx'
XDB=pd.read_excel(nxl,sheet_name=0)
XDB=XDB.dropna() #Elimina celdas vacias sin datos
XDB.head(100)

categorical_columns = ['Operating System', 'Gender', 'Device Model']
label_encoder = LabelEncoder()

for column in categorical_columns:
    XDB[column] = label_encoder.fit_transform(XDB[column])

#Se procede con la seleccion de las variabales de trabajo
XD=np.array(XDB[['App Usage Time (min/day)','Screen On Time (hours/day)','Battery Drain (mAh/day)','Number of Apps Installed','Data Usage (MB/day)','Age',]]) #Datos de entrada
print(XD)
yd=np.array(XDB[['User Behavior Class']]) #Este es el dato que quiero que el modelo pronostique
print(yd)

[[3.930e+02 6.400e+00 1.872e+03 6.700e+01 1.122e+03 4.000e+01]
 [2.680e+02 4.700e+00 1.331e+03 4.200e+01 9.440e+02 4.700e+01]
 [1.540e+02 4.000e+00 7.610e+02 3.200e+01 3.220e+02 4.200e+01]
 ...
 [9.900e+01 3.100e+00 9.420e+02 2.200e+01 4.570e+02 5.000e+01]
 [6.200e+01 1.700e+00 4.310e+02 1.300e+01 2.240e+02 4.400e+01]
 [2.120e+02 5.400e+00 1.306e+03 4.900e+01 8.280e+02 2.300e+01]]
[[4]
 [3]
 [2]
 [3]
 [3]
 [2]
 [4]
 [5]
 [4]
 [4]
 [1]
 [3]
 [4]
 [3]
 [3]
 [5]
 [2]
 [3]
 [1]
 [5]
 [2]
 [5]
 [4]
 [3]
 [3]
 [2]
 [4]
 [5]
 [4]
 [4]
 [3]
 [3]
 [3]
 [1]
 [5]
 [1]
 [2]
 [5]
 [4]
 [4]
 [3]
 [5]
 [2]
 [2]
 [2]
 [5]
 [5]
 [2]
 [5]
 [5]
 [4]
 [3]
 [2]
 [2]
 [5]
 [1]
 [1]
 [5]
 [4]
 [4]
 [5]
 [4]
 [1]
 [5]
 [4]
 [3]
 [3]
 [2]
 [5]
 [1]
 [4]
 [5]
 [4]
 [1]
 [1]
 [3]
 [1]
 [2]
 [1]
 [3]
 [5]
 [2]
 [4]
 [1]
 [3]
 [4]
 [2]
 [1]
 [2]
 [4]
 [2]
 [3]
 [1]
 [2]
 [4]
 [4]
 [5]
 [5]
 [1]
 [3]
 [1]
 [3]
 [2]
 [3]
 [2]
 [1]
 [2]
 [1]
 [3]
 [3]
 [2]
 [5]
 [3]
 [2]
 [4]
 [2]
 [1]
 [3]
 [1]
 [2]
 [4]
 [5]
 [5]
 

2. Creación del modelo - Decision Tree

In [ ]:
mar=DecisionTreeClassifier(criterion='gini',max_depth=5) #4 niveles o variables de entrada.
mar.fit(XD,yd)
ydp=mar.predict(XD)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(yd,ydp)
print(cm)

#Evaluamos el modelo
VN=cm[0,0]; FP=cm[0,1]; FN=cm[1,0]; VP=cm[1,1]

Ex=(VN+VP)/(VN+VP+FN+FP) #Que porcentaje de los datos pronostico correctamente
print("La exactitud alcanzada por el modelo es:", Ex)
Se=VP/(FN+VP) #Que porcentaje de los datos positivos pronosticado correctamente
print("La sensibilidad alcanzada por el modelo es:", Se)
Es=VN/(VN+FP) #Que porcentaje de los datos positivos pronosticado correctamente
print("La especificidad alcanzada por el modelo es:", Es)


[[136   0   0   0   0]
 [  0 146   0   0   0]
 [  0   0 143   0   0]
 [  0   0   0 139   0]
 [  0   0   0   0 136]]
La exactitud alcanzada por el modelo es: 1.0
La sensibilidad alcanzada por el modelo es: 1.0
La especificidad alcanzada por el modelo es: 1.0


3. Graficar el arbol

In [ ]:
#Estas son las librerias para graficar el arbol
from sklearn.tree import export_graphviz
from pydotplus import graph_from_dot_data

vs=['App Usage Time (min/day)','Screen On Time (hours/day)','Battery Drain (mAh/day)','Number of Apps Installed','Data Usage (MB/day)','Age'] #son los titulos para los nodos
dot_graph=export_graphviz(mar,feature_names=vs)
graph=graph_from_dot_data(dot_graph)
graph.write_png('arbol.png')

True

4. Se procede con el pronostico

In [ ]:
XDB2=pd.read_excel(nxl,sheet_name=0)
XDB2=XDB2.dropna() #Elimina celdas vacias sin datos
XDB2.head(100)

XD2=np.array(XDB2[['App Usage Time (min/day)','Screen On Time (hours/day)','Battery Drain (mAh/day)','Number of Apps Installed','Data Usage (MB/day)','Age']]) #Datos de entrada
print(XD2)

#Pronostico: User Behavior Class
ydp2=mar.predict(XD2)
print(ydp2)
print("User behavior class:",np.sum(ydp2))
print("El numero total de datos es:",len(ydp2))



[[3.930e+02 6.400e+00 1.872e+03 6.700e+01 1.122e+03 4.000e+01]
 [2.680e+02 4.700e+00 1.331e+03 4.200e+01 9.440e+02 4.700e+01]
 [1.540e+02 4.000e+00 7.610e+02 3.200e+01 3.220e+02 4.200e+01]
 ...
 [9.900e+01 3.100e+00 9.420e+02 2.200e+01 4.570e+02 5.000e+01]
 [6.200e+01 1.700e+00 4.310e+02 1.300e+01 2.240e+02 4.400e+01]
 [2.120e+02 5.400e+00 1.306e+03 4.900e+01 8.280e+02 2.300e+01]]
[4 3 2 3 3 2 4 5 4 4 1 3 4 3 3 5 2 3 1 5 2 5 4 3 3 2 4 5 4 4 3 3 3 1 5 1 2
 5 4 4 3 5 2 2 2 5 5 2 5 5 4 3 2 2 5 1 1 5 4 4 5 4 1 5 4 3 3 2 5 1 4 5 4 1
 1 3 1 2 1 3 5 2 4 1 3 4 2 1 2 4 2 3 1 2 4 4 5 5 1 3 1 3 2 3 2 1 2 1 3 3 2
 5 3 2 4 2 1 3 1 2 4 5 5 5 3 5 4 3 2 2 5 4 2 1 1 5 1 3 5 5 3 4 2 1 5 3 4 1
 3 2 5 1 2 4 1 2 1 4 4 2 1 1 4 1 3 5 5 1 3 5 2 1 2 4 1 3 3 3 3 5 2 4 5 1 5
 5 4 1 2 1 2 1 4 3 4 3 3 2 1 2 5 2 1 1 2 4 1 2 5 3 4 5 2 1 2 5 4 5 5 2 4 2
 4 5 2 5 4 3 2 4 2 5 5 2 2 1 5 4 1 5 1 5 2 4 1 3 1 4 2 1 1 4 5 2 1 4 4 3 3
 5 1 4 5 1 4 5 3 5 3 4 4 3 2 2 2 5 3 3 1 4 1 1 4 1 4 5 4 3 2 1 4 1 1 3 5 1
 4 2 3 2 4 3 4 5